#!/usr/bin/env zsh

# formats ls as a vertical list, excluding extra information from ls -l
# CLICOLOR_FORCE=1 forces ls colour to be displayed even through piping.
# LC_COLLATE=cs_CZ.ISO8859-2 is a locale that is used to sort the alphabet in a case-insensitive way (i.e. aAbBcC rather than abcABC).
# it does sort dotfiles after Z but we're getting there.
alias l=" CLICOLOR_FORCE=1 LC_COLLATE=cs_CZ.ISO8859-2 ls -lF   | awk '{$1=$2=$3=$4=$5=$6=$7=$8=""; if (NR!=1) print substr($0, 9)}'"
alias la="CLICOLOR_FORCE=1 LC_COLLATE=cs_CZ.ISO8859-2 ls -lFA  | awk '{$1=$2=$3=$4=$5=$6=$7=$8=""; if (NR!=1) print substr($0, 9)}'"

# git
alias g='git'
alias gch='git checkout'
alias gco='git commit'
alias gp='git push'

# kube
alias kc='kubectl'
alias kx='kubectx'
alias kn='kubens'
alias kwatch='watch -n 1 kubectl'
alias k='kubectl'

alias box='ssh adam@192.168.50.107 -i ~/.ssh/adam@box'

alias please='sudo'

alias tf='terraform'

alias vim="nvim"
